### ISSUE TITLE
Stage02 - Parallelization error

### ISSUE THREAD

**Issue by araihC** [NeuralEnsemble/cobrawap#25]
When running stage02 over the LENS dataset with a number of cores these errors occur:

`
Traceback (most recent call last):
  File "/Users/Mac/Desktop/wavescalephant-master/pipeline/scripts/utils.py", line 303, in load_neo
    raise e
  File "/Users/Mac/Desktop/wavescalephant-master/pipeline/scripts/utils.py", line 293, in load_neo
    io = neo.io.get_io(filename, *args, **kwargs)
  File "/anaconda3/envs/wavescalephant_env/lib/python3.8/site-packages/neo/io/__init__.py", line 334, in get_io
    return io(filename, *args, **kwargs)
  File "/anaconda3/envs/wavescalephant_env/lib/python3.8/site-packages/neo/io/nixio.py", line 196, in __init__
    self.nix_file = nix.File.open(self.filename, filemode)
  File "/anaconda3/envs/wavescalephant_env/lib/python3.8/site-packages/nixio/file.py", line 148, in open
    return cls(path, mode, compression, auto_update_timestamps)
  File "/anaconda3/envs/wavescalephant_env/lib/python3.8/site-packages/nixio/file.py", line 122, in __init__
    fid = h5py.h5f.open(path, flags=h5mode, fapl=make_fapl())
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/roi_selection.py", line 122, in <module>
    block = load_neo(args.data)
  File "/Users/Mac/Desktop/wavescalephant-master/pipeline/scripts/utils.py", line 305, in load_neo
    if not lazy and hasattr(io, 'close'):
UnboundLocalError: local variable 'io' referenced before assignment`

This does not happen when only 1 core is used.

**Comment by rgutzen** [comment]
Are you running the pipeline on a cluster? I'm getting the same error when using a cluster with an NFS filesystem, which does not support file locking. 
A quick fix for that is to manually set the corresponding environment variable 
```bash
export HDF5_USE_FILE_LOCKING=FALSE 
```

**Comment by rgutzen** [comment]
@araihC Is this issue resolved and can be closed?

**Comment by rgutzen** [comment]
closing due to inactivity. Feel free to reopen if the issue persists or reappears.
